name:  Exploring Variables
on: 
    workflow_dispatch: 
    push:

jobs:
    docker: 
        timeout-minutes: 1 
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build

    deploy: 
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: docker
        steps:
        - name: Docker Build
          timeout-minutes: 2
          run: |
           echo docker build
