name: Matrix Example

on:
  push:
  workflow_dispatch: 

jobs:
    docker:
        strategy:
          matrix: 
            os: [ubuntu-latest,windows-latest]
            images: [hello-world,alpine]
        runs-on: ${{matrix.os}}
        steps:
            - name: Run Images
              run: docker run ${{matrix.images}}
    