name:  Exploring Variables
on: 
  schedule:
    - cron: "*/10 * * * *"
jobs:
    docker: 
        runs-on: ubuntu:latest
        steps:
        - name: Docker Build
          run: echo docker build